# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-CheckManifest
version:      0.4
version_from: lib/Test/CheckManifest.pm
installdirs:  site
requires:
    Test::Builder:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
