---
abstract: 'Check if your Manifest matches your distro'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-CheckManifest
requires:
  Carp: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Find: '0'
  File::Spec: '0'
  Test::Builder: '0'
resources:
  bugtracker: http://github.com/reneeb/Test-CheckManifest/issues
  homepage: http://github.com/reneeb/Test-CheckManifest
  repository: http://github.com/reneeb/Test-CheckManifest.git
version: '1.29'
