--- #YAML:1.0
name:                Test-CheckManifest
version:             1.22
abstract:            Check if your Manifest matches your distro
license:             artistic_2
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:
    Carp:                          0
    Cwd:                           0
    File::Basename:                0
    File::Find:                    0
    File::Spec:                    0
    Test::Builder:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Renee Baecker <module@renee-baecker.de>

